- clean: ['~']

- link:
    ~/.gitconfig: git/gitconfig
    ~/.bin: bin/
    ~/.config/bspwm: bspwm/
    ~/.compton.conf: compton/compton.conf
    ~/.config/mpd: mpd/
    ~/.config/mpv: mpv/
    ~/.ncmpcpp: ncmpcpp/
    ~/.config/ranger: ranger/
    ~/.stalonetrayrc: stalonetray/stalonetrayrc
    ~/.config/sxhkd: sxhkd/
    ~/.vim: vim/
    ~/.vimrc: vim/vimrc
    ~/.vimperator: vimperator/
    ~/.vimperatorrc: vimperatorrc/vimperatorrc
    ~/.weechat: weechat/
    ~/.xinitrc: xorg/xinitrc
    ~/.Xresources: xorg/Xresources
    ~/.config/zathura: zathura/
    ~/.zsh: zsh/
    ~/.zshrc: zsh/zshrc

- shell:
    -
        - git update-submodules
        - Installing/updating submodules
    -
        - mkdir -p ~/.config/mpd/playlists
        - Creating mpd playlist directory
    -
        - touch ~/.config/mpd/{database,log,pid,state,sticker.sql}
        - Creating mpd files
    -
        - mkdir -p ~/.ncmpcpp/lyrics
        - creating ncmpcpp lyrics directory
